-- Query-ul trebuie rulat ca SYSDBA

-- Creare rol nou

CREATE ROLE SGBD_USER_ROLE;

-- Atribuire privilegii si roluri noului rol

GRANT CONNECT TO SGBD_USER_ROLE;
GRANT RESOURCE TO SGBD_USER_ROLE;
GRANT CREATE TABLE TO SGBD_USER_ROLE;
GRANT CREATE VIEW TO SGBD_USER_ROLE;
GRANT CREATE MATERIALIZED VIEW TO SGBD_USER_ROLE;
GRANT CREATE SYNONYM TO SGBD_USER_ROLE;
GRANT CREATE PROCEDURE TO SGBD_USER_ROLE;
GRANT CREATE SEQUENCE TO SGBD_USER_ROLE;
GRANT CREATE TRIGGER TO SGBD_USER_ROLE;
GRANT CREATE TYPE TO SGBD_USER_ROLE;
GRANT QUERY REWRITE TO SGBD_USER_ROLE;
GRANT SELECT_CATALOG_ROLE TO SGBD_USER_ROLE;
GRANT ALTER SESSION TO SGBD_USER_ROLE;
GRANT SELECT ANY DICTIONARY TO SGBD_USER_ROLE;
GRANT CREATE PUBLIC DATABASE LINK TO SGBD_USER_ROLE;
GRANT CREATE PUBLIC SYNONYM TO SGBD_USER_ROLE;

-- Creare utilizator nou

CREATE USER SGBD_USER IDENTIFIED BY SgbdProjectUser123
PROFILE DEFAULT
DEFAULT TABLESPACE USERS
QUOTA UNLIMITED ON USERS
ACCOUNT UNLOCK;

-- Atribuire rol la utilizator

GRANT SGBD_USER_ROLE TO SGBD_USER;

-- Atribuire privilegiu 

GRANT UNLIMITED TABLESPACE TO SGBD_USER;