-- Creare tabele

CREATE TABLE VALUTA (
    ID NUMBER(10) NOT NULL,
    COD VARCHAR2(5) NOT NULL,
    NUME VARCHAR2(100) NOT NULL,
    CONSTRAINT PK_VALUTA PRIMARY KEY (ID),
    CONSTRAINT UNIQUE_VALUTA_COD UNIQUE (COD)
);

CREATE TABLE VALUTA_CONVERSIE (
    ID NUMBER(10) NOT NULL,
    SURSA NUMBER(10) NOT NULL,
    DESTINATIE NUMBER(10) NOT NULL,
    RATA DECIMAL(10, 4) NOT NULL,
    DATA DATE NOT NULL,
    CONSTRAINT PK_VALUTA_CONVERSIE PRIMARY KEY (ID)
);

CREATE TABLE TARA (
    ID NUMBER(10) NOT NULL,
    NUME VARCHAR2(100) NOT NULL,
    COD VARCHAR2(5) NOT NULL,
    TIPAR_IBAN VARCHAR2(100) NOT NULL,
    CONSTRAINT PK_TARA PRIMARY KEY (ID),
    CONSTRAINT UNIQUE_TARA_COD UNIQUE (COD)
);

CREATE TABLE UTILIZATOR (
    ID NUMBER(10) NOT NULL,
    EMAIL VARCHAR2(100) NOT NULL,
    PAROLA VARCHAR2(1000) NOT NULL,
    NUME VARCHAR2(100) NOT NULL,
    PRENUME VARCHAR2(100) NOT NULL,
    CONSTRAINT PK_UTILIZATOR PRIMARY KEY (ID),
    CONSTRAINT UNQIUE_UTILIZATOR_EMAIL UNIQUE (EMAIL)
);

CREATE TABLE REZIDENTA_FISCALA (
    TARA NUMBER(10) NOT NULL,
    UTILIZATOR NUMBER(10) NOT NULL,
    CONSTRAINT PK_REZIDENTA_FISCALA PRIMARY KEY (TARA, UTILIZATOR)
);

CREATE TABLE CONT (
    ID NUMBER(10) NOT NULL,
    IBAN VARCHAR2(100) NOT NULL,
    VALUTA NUMBER(10) NOT NULL,
    TARA NUMBER(10) NOT NULL,
    SOLD DECIMAL(10, 2) NOT NULL,
    CONSTRAINT PK_CONT PRIMARY KEY (ID),
    CONSTRAINT UNIQUE_CONT_IBAN UNIQUE (IBAN)
);

CREATE TABLE CONT_UTILIZATOR (
    UTILIZATOR NUMBER(10) NOT NULL,
    CONT NUMBER(10) NOT NULL,
    CONSTRAINT PK_CONT_UTILIZATOR PRIMARY KEY (UTILIZATOR, CONT)
);

CREATE TABLE TRANZACTIE (
    ID NUMBER(10) NOT NULL,
    SURSA NUMBER(10) NOT NULL,
    DESTINATIE NUMBER(10) NOT NULL,
    SUMA DECIMAL(10, 2) NOT NULL,
    DATA DATE NOT NULL,
    VALUTA_CONVERSIE NUMBER(10) NOT NULL,
    CONSTRAINT PK_TRANZACTIE PRIMARY KEY (ID)
);

-- Creare constrangeri

ALTER TABLE VALUTA_CONVERSIE
    ADD CONSTRAINT FK_VALUTA_CONVERSIE_SURSA FOREIGN KEY(
        SURSA
    )
        REFERENCES VALUTA (
            ID
        );

ALTER TABLE VALUTA_CONVERSIE
    ADD CONSTRAINT FK_VALUTA_CONVERSIE_DESTINATIE FOREIGN KEY(
        DESTINATIE
    )
        REFERENCES VALUTA (
            ID
        );

ALTER TABLE REZIDENTA_FISCALA
    ADD CONSTRAINT FK_REZIDENTA_FISCALA_TARA FOREIGN KEY(
        TARA
    )
        REFERENCES TARA (
            ID
        );

ALTER TABLE REZIDENTA_FISCALA
    ADD CONSTRAINT FK_REZIDENTA_FISCALA_UTILIZATOR FOREIGN KEY(
        UTILIZATOR
    )
        REFERENCES UTILIZATOR (
            ID
        );

ALTER TABLE CONT
    ADD CONSTRAINT FK_CONT_VALUTA FOREIGN KEY(
        VALUTA
    )
        REFERENCES VALUTA (
            ID
        );

ALTER TABLE CONT
    ADD CONSTRAINT FK_CONT_TARA FOREIGN KEY(
        TARA
    )
        REFERENCES TARA (
            ID
        );

ALTER TABLE CONT_UTILIZATOR
    ADD CONSTRAINT FK_CONT_UTILIZATOR_UTILIZATOR FOREIGN KEY(
        UTILIZATOR
    )
        REFERENCES UTILIZATOR (
            ID
        );

ALTER TABLE CONT_UTILIZATOR
    ADD CONSTRAINT FK_CONT_UTILIZATOR_CONT FOREIGN KEY(
        CONT
    )
        REFERENCES CONT (
            ID
        );

ALTER TABLE TRANZACTIE
    ADD CONSTRAINT FK_TRANZACTIE_SURSA FOREIGN KEY(
        SURSA
    )
        REFERENCES CONT (
            ID
        );

ALTER TABLE TRANZACTIE
    ADD CONSTRAINT FK_TRANZACTIE_DESTINATIE FOREIGN KEY(
        DESTINATIE
    )
        REFERENCES CONT (
            ID
        );

ALTER TABLE TRANZACTIE
    ADD CONSTRAINT FK_TRANZACTIE_VALUTA_CONVERSIE FOREIGN KEY(
        VALUTA_CONVERSIE
    )
        REFERENCES VALUTA_CONVERSIE (
            ID
        );