DROP TABLE VALUTA CASCADE CONSTRAINTS;

DROP TABLE VALUTA_CONVERSIE CASCADE CONSTRAINTS;

DROP TABLE TARA CASCADE CONSTRAINTS;

DROP TABLE UTILIZATOR CASCADE CONSTRAINTS;

DROP TABLE REZIDENTA_FISCALA CASCADE CONSTRAINTS;

DROP TABLE CONT CASCADE CONSTRAINTS;

DROP TABLE CONT_UTILIZATOR CASCADE CONSTRAINTS;

DROP TABLE TRANZACTIE CASCADE CONSTRAINTS;