CREATE OR REPLACE TRIGGER VALIDARE_LOC_REZERVARE_SALA BEFORE
    UPDATE OR INSERT OF ID_LOC ON REZERVARI FOR EACH ROW
DECLARE
    ID_SALA_LOC      SALI.ID_SALA%TYPE;
    ID_SALA_DIFUZARE SALI.ID_SALA%TYPE;
BEGIN
    SELECT
        L.ID_SALA INTO ID_SALA_LOC
    FROM
        LOCURI L
    WHERE
        L.ID_LOC = :NEW.ID_LOC;
    SELECT
        D.ID_SALA INTO ID_SALA_DIFUZARE
    FROM
        DIFUZARI D
    WHERE
        D.ID_DIFUZARE = :NEW.ID_DIFUZARE;
    IF ID_SALA_LOC != ID_SALA_DIFUZARE THEN
        RAISE_APPLICATION_ERROR(-20004, 'Locul asociat rezervarii nu se afla in sala unde se difuzeaza filmul!');
    END IF;
END;