DECLARE
BEGIN
    BEGIN INSERT INTO REZERVARI VALUES (
        ID_LOC_REZERVARE,
        ID_DIFUZARE_REZERVARE,
        ID_CLIENT_REZERVARE
    );
EXCEPTION
    WHEN OTHERS THEN
        DBMS_OUTPUT.PUT_LINE('Eroare! '
                             || SUBSTR(SQLERRM, 1, 255));
END;
BEGIN
    UPDATE END;