DROP TYPE REZERVARI_CLIENT_DATE_DIFUZARI;

DROP TYPE REZERVARI_CLIENT_DATE_DIFUZARE;

DROP TYPE LISTA_CODURI_LOCURI;

CREATE OR REPLACE TYPE LISTA_CODURI_LOCURI IS
    VARRAY(20) OF VARCHAR2(20);
/

CREATE OR REPLACE TYPE REZERVARI_CLIENT_DATE_DIFUZARE IS
    OBJECT (
        TITLU_FILM VARCHAR2(255),
        DATA_DIFUZARE DATE,
        CODURI_LOCURI LISTA_CODURI_LOCURI
    )
/

CREATE OR REPLACE TYPE REZERVARI_CLIENT_DATE_DIFUZARI IS
    TABLE OF REZERVARI_CLIENT_DATE_DIFUZARE;
/

ALTER TABLE CLIENTI
    ADD DATE_REZERVARI REZERVARI_CLIENT_DATE_DIFUZARI NESTED TABLE DATE_REZERVARI STORE AS DATE_REZERVARI_TI;

CREATE OR REPLACE FUNCTION REZERVARI_CLIENT (
    ID_CLIENT_PARAM CLIENTI.ID_CLIENT%TYPE
) RETURN REZERVARI_CLIENT_DATE_DIFUZARI AS
    TYPE LOCURI_DIFUZARE IS
        TABLE OF LISTA_CODURI_LOCURI INDEX BY BINARY_INTEGER;
    DATE_LOCURI_DIFUZARE     LOCURI_DIFUZARE;
    DATE_CLIENT              REZERVARI_CLIENT_DATE_DIFUZARI;
    DATE_LISTA_CODURI_LOCURI LISTA_CODURI_LOCURI;
BEGIN
    DATE_CLIENT := REZERVARI_CLIENT_DATE_DIFUZARI();
    FOR DATE_REZERVARE IN (
        SELECT
            R.ID_DIFUZARE,
            L.COD
        FROM
            (
                SELECT
                    *
                FROM
                    REZERVARI R
                WHERE
                    R.ID_CLIENT = ID_CLIENT_PARAM
            ) R
            INNER JOIN LOCURI L
            ON L.ID_LOC = R.ID_LOC
    ) LOOP
        BEGIN
            DATE_LISTA_CODURI_LOCURI := DATE_LOCURI_DIFUZARE(DATE_REZERVARE.ID_DIFUZARE);
        EXCEPTION
            WHEN NO_DATA_FOUND THEN
                DATE_LISTA_CODURI_LOCURI := LISTA_CODURI_LOCURI();
        END;

        DATE_LISTA_CODURI_LOCURI.EXTEND;
        DATE_LISTA_CODURI_LOCURI(DATE_LISTA_CODURI_LOCURI.COUNT) := DATE_REZERVARE.COD;
        DATE_LOCURI_DIFUZARE(DATE_REZERVARE.ID_DIFUZARE) := DATE_LISTA_CODURI_LOCURI;
    END LOOP;

    FOR DATE_DIFUZARE IN (
        SELECT
            D.ID_DIFUZARE,
            D.DATA,
            F.TITLU
        FROM
            (
                SELECT
                    R.ID_DIFUZARE
                FROM
                    REZERVARI R
                WHERE
                    R.ID_CLIENT = ID_CLIENT_PARAM
                GROUP BY
                    R.ID_DIFUZARE
            ) DC
            INNER JOIN DIFUZARI D
            ON DC.ID_DIFUZARE = D.ID_DIFUZARE
            INNER JOIN FILME F
            ON F.ID_FILM = D.ID_FILM
    ) LOOP
        DATE_LISTA_CODURI_LOCURI := DATE_LOCURI_DIFUZARE(DATE_DIFUZARE.ID_DIFUZARE);
        DATE_CLIENT.EXTEND;
        DATE_CLIENT(DATE_CLIENT.COUNT) := REZERVARI_CLIENT_DATE_DIFUZARE(DATE_DIFUZARE.TITLU, DATE_DIFUZARE.DATA, DATE_LISTA_CODURI_LOCURI);
    END LOOP;
    UPDATE CLIENTI C
    SET
        DATE_REZERVARI = DATE_CLIENT
    WHERE
        C.ID_CLIENT = ID_CLIENT_PARAM;
    RETURN DATE_CLIENT;
END REZERVARI_CLIENT;

CREATE OR REPLACE TRIGGER ACTUALIZEAZA_REZERVARI_CLIENT AFTER
DELETE
OR UPDATE
OR INSERT OF ID_CLIENT ON REZERVARI 
DECLARE 

BEGIN 
END ACTUALIZEAZA_REZERVARI_CLIENT;