CREATE OR REPLACE PACKAGE CONSTANTE_GLOBALE AS
    LOCURI_PER_SALA          NUMBER(10);
    REZERVARI_PER_CLIENT_MAX NUMBER(10);
    NUMAR_DIFUZARI           NUMBER(10);
END CONSTANTE_GLOBALE;
/

CREATE OR REPLACE PACKAGE BODY CONSTANTE_GLOBALE AS
    LOCURI_PER_SALA          NUMBER(10) := 30;
    REZERVARI_PER_CLIENT_MAX NUMBER(10) := 5;
    NUMAR_DIFUZARI           NUMBER(10) := 50;
END CONSTANTE_GLOBALE;
/

CREATE OR REPLACE PACKAGE GENERATOR_DE_DATE_ALEATOARE AS

    FUNCTION LOC_ALEATOR_IN_SALA (
        ID_SALA IN SALI.ID_SALA%TYPE
    ) RETURN LOCURI.ID_LOC%TYPE;

    FUNCTION LOC_ALEATOR_LA_DIFUZARE (
        ID_DIFUZARE IN DIFUZARI.ID_DIFUZARE%TYPE
    ) RETURN DIFUZARI.ID_DIFUZARE%TYPE;
END GENERATOR_DE_DATE_ALEATOARE;
/

CREATE OR REPLACE PACKAGE BODY GENERATOR_DE_DATE_ALEATOARE AS

    FUNCTION LOC_ALEATOR_IN_SALA (
        ID_SALA IN SALI.ID_SALA%TYPE
    ) RETURN LOCURI.ID_LOC%TYPE IS
        ID_LOC LOCURI.ID_LOC%TYPE;
    BEGIN
        ID_LOC := (ID_SALA - 1) * CONSTANTE_GLOBALE.LOCURI_PER_SALA + DBMS_RANDOM.VALUE(1, CONSTANTE_GLOBALE.LOCURI_PER_SALA);
        RETURN ID_LOC;
    END LOC_ALEATOR_IN_SALA;

    FUNCTION LOC_ALEATOR_LA_DIFUZARE (
        ID_DIFUZARE IN DIFUZARI.ID_DIFUZARE%TYPE
    ) RETURN LOC.ID_LOC%TYPE AS
        ID_SALA SALI.ID_SALA%TYPE;
        ID_LOC  LOCURI.ID_LOC%TYPE;
    BEGIN
        SELECT
            D.ID_SALA INTO ID_SALA
        FROM
            DIFUZARI D
        WHERE
            D.ID_DIFUZARE = ID_DIFUZARE;
        ID_LOC := LOC_ALEATOR_IN_SALA(ID_SALA);
        RETURN ID_LOC;
    END LOC_ALEATOR_LA_DIFUZARE;
END GENERATOR_DE_DATE_ALEATOARE;