CREATE TABLE CINEMATOGRAFE_AUXILIAR AS (
    SELECT
        *
    FROM
        SGBD_USER.CINEMATOGRAFE
);

SELECT
    *
FROM
    CINEMATOGRAFE_AUXILIAR;

ALTER TABLE CINEMATOGRAFE_AUXILIAR
    ADD STATISTICA_AUXILIARA NUMBER(
        10,
        4
    );

DROP TABLE CINEMATOGRAFE_AUXILIAR;

SELECT * FROM BACKUP_1_CINEMATOGRAFE_AUXILIAR;

SELECT * FROM BACKUP_2_CINEMATOGRAFE_AUXILIAR;
