CREATE OR REPLACE PACKAGE PACHET_DIFUZARI AS

    FUNCTION CAUTA_DIFUZARI_DUPA_CONDITIE(
        CONDITIE_PARAM VARCHAR2
    ) RETURN SYS_REFCURSOR;

    FUNCTION CAUTA_DIFUZARI_DUPA_SALA(
        ID_SALA_PARAM SALI.ID_SALA%TYPE
    ) RETURN SYS_REFCURSOR;
END PACHET_DIFUZARI;
/

CREATE OR REPLACE PACKAGE BODY PACHET_DIFUZARI AS

    FUNCTION CAUTA_DIFUZARI_DUPA_CONDITIE(
        CONDITIE_PARAM VARCHAR2
    ) RETURN SYS_REFCURSOR IS
        CURSOR_DATE   SYS_REFCURSOR;
        QUERY_CAUTARE VARCHAR2(1000);
    BEGIN
        QUERY_CAUTARE := 'SELECT * FROM DIFUZARI D WHERE 1=1 AND '
                         || CONDITIE_PARAM;
        OPEN CURSOR_DATE FOR QUERY_CAUTARE;
        RETURN CURSOR_DATE;
    END;

    FUNCTION CAUTA_DIFUZARI_DUPA_SALA(
        ID_SALA_PARAM SALI.ID_SALA%TYPE
    ) RETURN SYS_REFCURSOR IS
        CURSOR_DATE   SYS_REFCURSOR;
        QUERY_CAUTARE VARCHAR2(1000);
    BEGIN
        QUERY_CAUTARE := 'SELECT * FROM DIFUZARI D WHERE D.ID_SALA = :ID';
        OPEN CURSOR_DATE FOR QUERY_CAUTARE
            USING ID_SALA_PARAM;
        RETURN CURSOR_DATE;
    END;
END PACHET_DIFUZARI;
/

DECLARE
    CURSOR_DATE SYS_REFCURSOR;
    CONDITIE    VARCHAR2(255) := 'D.PRET BETWEEN 15 AND 25';
    ID_SALA     SALI.ID_SALA%TYPE := 5;

    PROCEDURE AFISARE_DATE_CURSOR(
        CURSOR_DATE_PARAM SYS_REFCURSOR
    ) IS
        DATE_DIFUZARE DIFUZARI%ROWTYPE;
    BEGIN
        LOOP
            FETCH CURSOR_DATE_PARAM INTO DATE_DIFUZARE;
            EXIT WHEN CURSOR_DATE_PARAM%NOTFOUND;
            DBMS_OUTPUT.PUT_LINE('Difuzarea '
                                 || DATE_DIFUZARE.ID_DIFUZARE);
            DBMS_OUTPUT.PUT_LINE('Sala '
                                 || DATE_DIFUZARE.ID_SALA);
            DBMS_OUTPUT.PUT_LINE('Data '
                                 || TO_CHAR(DATE_DIFUZARE.DATA, 'dd.mm.yyyy'));
            DBMS_OUTPUT.PUT_LINE('Pret '
                                 || DATE_DIFUZARE.PRET);
            DBMS_OUTPUT.NEW_LINE();
        END LOOP;
    END;
BEGIN
    CURSOR_DATE := PACHET_DIFUZARI.CAUTA_DIFUZARI_DUPA_CONDITIE(CONDITIE);
    AFISARE_DATE_CURSOR(CURSOR_DATE);
    DBMS_OUTPUT.NEW_LINE();
    CURSOR_DATE := PACHET_DIFUZARI.CAUTA_DIFUZARI_DUPA_SALA(ID_SALA);
    AFISARE_DATE_CURSOR(CURSOR_DATE);
END;