DECLARE
    ID_DIFUZARE DIFUZARI.ID_DIFUZARE%TYPE := &ID_DIFUZARE;
    DATE_LOCURI OCUPARE_LOCURI_LA_DIFUZARE_DATE_LOCURI;
    DATE_LOC    OCUPARE_LOCURI_LA_DIFUZARE_DATE_LOC;
BEGIN
    DATE_LOCURI := OCUPARE_LOCURI_LA_DIFUZARE(ID_DIFUZARE);
    FOR INDEX_DATE_LOC IN DATE_LOCURI.FIRST..DATE_LOCURI.LAST LOOP
        DATE_LOC := DATE_LOCURI(INDEX_DATE_LOC);
        DBMS_OUTPUT.PUT_LINE('Cod loc: '
                             || DATE_LOC.COD_LOC);
        DBMS_OUTPUT.PUT_LINE('Status: '
                             || DATE_LOC.STATUS);
        IF DATE_LOC.NUME_COMPLET IS NOT NULL THEN
            DBMS_OUTPUT.PUT_LINE('Nume persoana: '
                                 || DATE_LOC.NUME_COMPLET);
        END IF;

        DBMS_OUTPUT.NEW_LINE();
    END LOOP;
END;