CREATE TABLE LOCATION (
    LOCATION_ID NUMBER(10) NOT NULL,
    COUNTRY VARCHAR2(255) NOT NULL,
    CITY VARCHAR2(255) NOT NULL,
    STREET VARCHAR2(255) NOT NULL,
    "NUMBER" NUMBER(10) NOT NULL,
    CONSTRAINT LOCATION_PK PRIMARY KEY (LOCATION_ID)
);

CREATE TABLE CINEMA (
    CINEMA_ID NUMBER(10) NOT NULL,
    LOCATION_ID NUMBER(10) NOT NULL,
    NAME VARCHAR2(255) NOT NULL,
    CONSTRAINT CINEMA_PK PRIMARY KEY (CINEMA_ID),
    CONSTRAINT CINEMA_LOCATION_PK FOREIGN KEY (LOCATION_ID) REFERENCES LOCATION(LOCATION_ID)
);

CREATE TABLE EMPLOYEE (
    EMPLOYEE_ID NUMBER(10) NOT NULL,
    MANAGER_ID NUMBER(10),
    FIRST_NAME VARCHAR2(255) NOT NULL,
    LAST_NAME VARCHAR2(255) NOT NULL,
    CONSTRAINT EMPLOYEE_PK PRIMARY KEY (EMPLOYEE_ID)
);

ALTER TABLE EMPLOYEE
    ADD CONSTRAINT EMPLOYEE_MANAGER_PK FOREIGN KEY (
        MANAGER_ID
    )
        REFERENCES EMPLOYEE(
            EMPLOYEE_ID
        );

CREATE TABLE JOB (
    JOB_ID NUMBER(10) NOT NULL,
    EMPLOYEE_ID NUMBER(10) NOT NULL,
    CINEMA_ID NUMBER(10) NOT NULL,
    START_DATE DATE NOT NULL,
    END_DATE DATE NOT NULL,
    CONSTRAINT JOB_PK PRIMARY KEY (JOB_ID),
    CONSTRAINT JOB_EMPLOYEE_FK FOREIGN KEY (EMPLOYEE_ID) REFERENCES EMPLOYEE(EMPLOYEE_ID),
    CONSTRAINT JOB_CINEMA_FK FOREIGN KEY (CINEMA_ID) REFERENCES CINEMA(CINEMA_ID)
);

CREATE TABLE AUDITORIUM (
    AUDITORIUM_ID NUMBER(10) NOT NULL,
    CINEMA_ID NUMBER(10) NOT NULL,
    "NUMBER" NUMBER(10) NOT NULL,
    CONSTRAINT AUDITORIUM_PK PRIMARY KEY (AUDITORIUM_ID),
    CONSTRAINT AUDITORIUM_CINEMA_FK FOREIGN KEY (CINEMA_ID) REFERENCES CINEMA(CINEMA_ID)
);

CREATE TABLE SEAT (
    SEAT_ID NUMBER(10) NOT NULL,
    AUDITORIUM_ID NUMBER(10) NOT NULL,
    "NUMBER" NUMBER(10) NOT NULL,
    CONSTRAINT SEAT_PK PRIMARY KEY (SEAT_ID),
    CONSTRAINT SEAT_AUDITORIUM_FK FOREIGN KEY (AUDITORIUM_ID) REFERENCES AUDITORIUM(AUDITORIUM_ID)
);

CREATE TABLE CATEGORY (
    CATEGORY_ID NUMBER(10) NOT NULL,
    "NAME" VARCHAR2(255) NOT NULL,
    DESCRIPTION VARCHAR2(1000) NOT NULL,
    CONSTRAINT CATEGORY_PK PRIMARY KEY (CATEGORY_ID)
);

CREATE TABLE MOVIE (
    MOVIE_ID NUMBER(10) NOT NULL,
    TITLE VARCHAR2(255) NOT NULL,
    DURATION NUMBER(10) NOT NULL,
    RELEASE_DATE DATE NOT NULL,
    CONSTRAINT MOVIE_PK PRIMARY KEY (MOVIE_ID)
);

CREATE TABLE MOVIE_CATEGORY (
    MOVIE_ID NUMBER(10) NOT NULL,
    CATEGORY_ID NUMBER(10) NOT NULL,
    CONSTRAINT MOVIE_CATEGORY_PK PRIMARY KEY (MOVIE_ID, CATEGORY_ID)
);

CREATE TABLE SCREENING (
    SCREENING_ID NUMBER(10) NOT NULL,
    AUDITORIUM_ID NUMBER(10) NOT NULL,
    MOVIE_ID NUMBER(10) NOT NULL,
    "DATE" DATE NOT NULL,
    PRICE NUMBER(10) NOT NULL,
    CONSTRAINT SCREENING_PK PRIMARY KEY (SCREENING_ID),
    CONSTRAINT SCREENING_AUDITORIUM_FK FOREIGN KEY (AUDITORIUM_ID) REFERENCES AUDITORIUM(AUDITORIUM_ID),
    CONSTRAINT SCREENING_MOVIE_FK FOREIGN KEY (MOVIE_ID) REFERENCES MOVIE(MOVIE_ID)
);

CREATE TABLE CLIENT (
    CLIENT_ID NUMBER(10) NOT NULL,
    FIRST_NAME VARCHAR2(255) NOT NULL,
    LAST_NAME VARCHAR2(255) NOT NULL,
    EMAIL VARCHAR2(255) NOT NULL,
    PHONE_NUMBER VARCHAR2(255) NOT NULL,
    CONSTRAINT CLIENT_PK PRIMARY KEY (CLIENT_ID)
);

CREATE TABLE RESERVATION (
    SEAT_ID NUMBER(10) NOT NULL,
    SCREENING_ID NUMBER(10) NOT NULL,
    CLIENT_ID NUMBER(10) NOT NULL,
    CONSTRAINT SEAT_SCREENING_CLIENT_PK PRIMARY KEY (SEAT_ID, SCREENING_ID, CLIENT_ID)
);

COMMIT;