ALTER TABLE CINEMATOGRAFE
    ADD MEDIE_REZERVARI_PER_DIFUZARE NUMBER(
        10,
        4
    );

/

CREATE OR REPLACE PROCEDURE ACTUALIZEAZA_MEDIE_REZERVARI_PER_DIFUZARE AS
BEGIN
    FOR DATE_REZERVARI IN (
        SELECT
            S.ID_CINEMATOGRAF,
            AVG(NUMAR_REZERVARI) AS MEDIE_REZERVARI_PER_DIFUZARE
        FROM
            (
                SELECT
                    D.ID_DIFUZARE,
                    D.ID_SALA,
                    COUNT(R.ID_LOC) AS NUMAR_REZERVARI
                FROM
                    DIFUZARI  D
                    INNER JOIN REZERVARI R
                    ON R.ID_DIFUZARE = D.ID_DIFUZARE
                GROUP BY
                    D.ID_DIFUZARE,
                    D.ID_SALA
            )    DR
            INNER JOIN SALI S
            ON S.ID_SALA = DR.ID_SALA
        GROUP BY
            S.ID_CINEMATOGRAF
    ) LOOP
        UPDATE CINEMATOGRAFE C
        SET
            C.MEDIE_REZERVARI_PER_DIFUZARE = DATE_REZERVARI.MEDIE_REZERVARI_PER_DIFUZARE
        WHERE
            C.ID_CINEMATOGRAF = DATE_REZERVARI.ID_CINEMATOGRAF;
    END LOOP;
END ACTUALIZEAZA_MEDIE_REZERVARI_PER_DIFUZARE;
/

BEGIN
    ACTUALIZEAZA_MEDIE_REZERVARI_PER_DIFUZARE();
END;
/

CREATE OR REPLACE TRIGGER ACTUALIZEAZA_MEDIE_REZERVARI_PER_DIFUZARE_TRIGGER AFTER
    DELETE OR UPDATE OR INSERT OF ID_DIFUZARE ON REZERVARI
BEGIN
    ACTUALIZEAZA_MEDIE_REZERVARI_PER_DIFUZARE();
END;