CREATE TABLE LOCATII (
    ID_LOCATIE NUMBER(10) NOT NULL,
    TARA VARCHAR2(255) NOT NULL,
    ORAS VARCHAR2(255) NOT NULL,
    ADRESA VARCHAR2(255) NOT NULL,
    COD_POSTAL VARCHAR2(10) NOT NULL,
    CONSTRAINT LOCATII_PK PRIMARY KEY (ID_LOCATIE)
);

CREATE TABLE CINEMATOGRAFE (
    ID_CINEMATOGRAF NUMBER(10) NOT NULL,
    ID_LOCATIE NUMBER(10) NOT NULL,
    NUME VARCHAR2(255) NOT NULL,
    CONSTRAINT CINEMATOGRAFE_PK PRIMARY KEY (ID_CINEMATOGRAF),
    CONSTRAINT CINEMATOGRAFE_LOCATIE_FK FOREIGN KEY (ID_LOCATIE) REFERENCES LOCATII(ID_LOCATIE)
);

CREATE TABLE ANGAJATI (
    ID_ANGAJAT NUMBER(10) NOT NULL,
    ID_MANAGER NUMBER(10),
    NUME VARCHAR2(255) NOT NULL,
    PRENUME VARCHAR2(255) NOT NULL,
    CONSTRAINT ANGAJATI_PK PRIMARY KEY (ID_ANGAJAT)
);

ALTER TABLE ANGAJATI
    ADD CONSTRAINT ANGAJATI_MANAGER_FK FOREIGN KEY (
        ID_MANAGER
    )
        REFERENCES ANGAJATI(
            ID_ANGAJAT
        );

CREATE TABLE POSTURI (
    ID_POST NUMBER(10) NOT NULL,
    ID_ANGAJAT NUMBER(10) NOT NULL,
    ID_CINEMATOGRAF NUMBER(10) NOT NULL,
    DATA_INCEPUT DATE NOT NULL,
    DATA_SFARSIT DATE,
    CONSTRAINT POSTURI_PK PRIMARY KEY (ID_POST),
    CONSTRAINT POSTURI_ANGAJAT_FK FOREIGN KEY (ID_ANGAJAT) REFERENCES ANGAJATI(ID_ANGAJAT),
    CONSTRAINT POSTURI_CINEMATOGRAF_FK FOREIGN KEY (ID_CINEMATOGRAF) REFERENCES CINEMATOGRAFE(ID_CINEMATOGRAF)
);

CREATE TABLE SALI (
    ID_SALA NUMBER(10) NOT NULL,
    ID_CINEMATOGRAF NUMBER(10) NOT NULL,
    COD VARCHAR2(255) NOT NULL,
    CONSTRAINT SALI_PK PRIMARY KEY (ID_SALA),
    CONSTRAINT SALI_CINEMATOGRAF_FK FOREIGN KEY (ID_CINEMATOGRAF) REFERENCES CINEMATOGRAFE(ID_CINEMATOGRAF)
);

CREATE TABLE LOCURI (
    ID_LOC NUMBER(10) NOT NULL,
    ID_SALA NUMBER(10) NOT NULL,
    COD VARCHAR2(20) NOT NULL,
    CONSTRAINT LOCURI_PK PRIMARY KEY (ID_LOC),
    CONSTRAINT LOCURI_SALA_FK FOREIGN KEY (ID_SALA) REFERENCES SALI(ID_SALA)
);

CREATE TABLE CATEGORII (
    ID_CATEGORIE NUMBER(10) NOT NULL,
    NUME VARCHAR2(255) NOT NULL,
    DESCRIERE VARCHAR2(1000),
    CONSTRAINT CATEGORII_PK PRIMARY KEY (ID_CATEGORIE)
);

CREATE TABLE FILME (
    ID_FILM NUMBER(10) NOT NULL,
    TITLU VARCHAR2(255) NOT NULL,
    DURATA NUMBER(10) NOT NULL,
    DATA_PUBLICARE DATE NOT NULL,
    CONSTRAINT FILME_PK PRIMARY KEY (ID_FILM)
);

CREATE TABLE CATEGORII_FILME (
    ID_FILM NUMBER(10) NOT NULL,
    ID_CATEGORIE NUMBER(10) NOT NULL,
    CONSTRAINT CATEGORII_FILME_PK PRIMARY KEY (ID_FILM, ID_CATEGORIE)
);

CREATE TABLE DIFUZARI (
    ID_DIFUZARE NUMBER(10) NOT NULL,
    ID_SALA NUMBER(10) NOT NULL,
    ID_FILM NUMBER(10) NOT NULL,
    DATA DATE NOT NULL,
    PRET NUMBER(10) NOT NULL,
    CONSTRAINT DIFUZARI_PK PRIMARY KEY (ID_DIFUZARE),
    CONSTRAINT DIFUZARI_SALA_FK FOREIGN KEY (ID_SALA) REFERENCES SALI(ID_SALA),
    CONSTRAINT DIFUZARI_FILM_FK FOREIGN KEY (ID_FILM) REFERENCES FILME(ID_FILM)
);

CREATE TABLE CLIENTI (
    ID_CLIENT NUMBER(10) NOT NULL,
    NUME VARCHAR2(255) NOT NULL,
    PRENUME VARCHAR2(255) NOT NULL,
    EMAIL VARCHAR2(255) NOT NULL,
    TELEFON VARCHAR2(255) NOT NULL,
    CONSTRAINT CLIENTI_PK PRIMARY KEY (ID_CLIENT),
    CONSTRAINT CLIENTI_EMAIL_UNIQUE UNIQUE (EMAIL)
);

CREATE TABLE REZERVARI (
    ID_LOC NUMBER(10) NOT NULL,
    ID_DIFUZARE NUMBER(10) NOT NULL,
    ID_CLIENT NUMBER(10) NOT NULL,
    DATA DATE DEFAULT SYSDATE NOT NULL,
    CONSTRAINT REZERVARI_PK PRIMARY KEY (ID_LOC, ID_DIFUZARE, ID_CLIENT)
);

COMMIT;