SET VERIFY OFF

SET FEEDBACK ON

SET SERVEROUTPUT ON

CREATE OR REPLACE TYPE NAME_LIST AS
    VARRAY(10) OF VARCHAR2(255);
/

CREATE TABLE SHARE_LAST_NAME (
    LAST_NAME VARCHAR2(255),
    FIRST_NAMES NAME_LIST
);

DECLARE
    NAMES NAME_LIST;
BEGIN
    FOR ITEM IN (
        SELECT
            C1.LAST_NAME
        FROM
            CLIENT C1
            INNER JOIN CLIENT C2
            ON UPPER(C1.LAST_NAME) = UPPER(C2.LAST_NAME)
            AND C1.CLIENT_ID < C2.CLIENT_ID
        GROUP BY
            C1.LAST_NAME
    ) LOOP
        SELECT
            UPPER(C.FIRST_NAME) BULK COLLECT INTO NAMES
        FROM
            CLIENT C
        WHERE
            UPPER(C.LAST_NAME) = UPPER(ITEM.LAST_NAME);
        INSERT INTO SHARE_LAST_NAME VALUES(
            UPPER(ITEM.LAST_NAME),
            NAMES
        );
    END LOOP;

    FOR ITEM IN (
        SELECT
            *
        FROM
            SHARE_LAST_NAME
    ) LOOP
        DBMS_OUTPUT.PUT_LINE(ITEM.LAST_NAME
                             || ':');
        FOR VALUE_INDEX IN ITEM.FIRST_NAMES.FIRST..ITEM.FIRST_NAMES.LAST LOOP
            DBMS_OUTPUT.PUT_LINE(ITEM.FIRST_NAMES(VALUE_INDEX));
        END LOOP;

        DBMS_OUTPUT.PUT_LINE('');
    END LOOP;
END;
/

DROP TABLE SHARE_LAST_NAME;

DROP TYPE NAME_LIST;