CREATE OR REPLACE TRIGGER UPDATE_MOVIE_STATISTICS AFTER
    INSERT ON RESERVATION FOR EACH ROW
DECLARE
    ID_MOVIE MOVIE.MOVIE_ID%TYPE;
    AVERAGE  MOVIE_STATISTICS.RESERVATIONS_PER_SCREENING_AVERAGE%TYPE;
BEGIN
    SELECT
        S.MOVIE_ID INTO ID_MOVIE
    FROM
        SCREENING S
    WHERE
        S.SCREENING_ID = :NEW.SCREENING_ID;
    SELECT
        AVG(SEAT_COUNT) INTO AVERAGE
    FROM
        (
            SELECT
                S.SCREENING_ID,
                COUNT(R.SEAT_ID) AS SEAT_COUNT
            FROM
                SCREENING   S
                INNER JOIN RESERVATION R
                ON R.SCREENING_ID = S.SCREENING_ID
            WHERE
                S.MOVIE_ID = ID_MOVIE
            GROUP BY
                S.SCREENING_ID
        );
    UPDATE MOVIE_STATISTICS
    SET
        RESERVATIONS_PER_SCREENING_AVERAGE = AVERAGE
    WHERE
        MOVIE_ID = ID_MOVIE;
END;