DECLARE
    ID_CLIENT     CLIENTI.ID_CLIENT%TYPE := &ID_CLIENT;
    DATE_CLIENT   REZERVARI_CLIENT_DATE_DIFUZARI;
    DATE_DIFUZARE REZERVARI_CLIENT_DATE_DIFUZARE;
    LISTA_LOCURI  VARCHAR2(255);
BEGIN
    DATE_CLIENT := REZERVARI_CLIENT(ID_CLIENT);
    FOR INDEX_DIFUZARE IN DATE_CLIENT.FIRST..DATE_CLIENT.LAST LOOP
        DATE_DIFUZARE := DATE_CLIENT(INDEX_DIFUZARE);
        DBMS_OUTPUT.PUT_LINE('Film: '
                             || DATE_DIFUZARE.TITLU_FILM);
        DBMS_OUTPUT.PUT_LINE('Data: '
                             || TO_CHAR(DATE_DIFUZARE.DATA_DIFUZARE, 'dd.mm.yyyy'));
        LISTA_LOCURI := '';
        FOR INDEX_COD_LOC IN DATE_DIFUZARE.CODURI_LOCURI.FIRST..DATE_DIFUZARE.CODURI_LOCURI.LAST LOOP
            LISTA_LOCURI := LISTA_LOCURI
                            || DATE_DIFUZARE.CODURI_LOCURI(INDEX_COD_LOC)
                            || ' ';
        END LOOP;

        DBMS_OUTPUT.PUT_LINE('Coduri locuri: '
                             || LISTA_LOCURI);
        DBMS_OUTPUT.NEW_LINE();
    END LOOP;
END;